version: '3.8'
services:
  convo:
    build:
      context: ./convo-service
    volumes:
      - /usr/app/node_modules
      - ./convo-service/dist:/usr/app/dist
    networks:
      - bot
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 15673:15672
    networks:
        - bot 
networks:
  bot:
    driver: bridge
